name = "Essentials"
author = "Fuzz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9ef221b532b79aeeb0f81f497deec543304527f10d768866ea7a1d798a04a20"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
